// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace app_house.Migrations
{
    [DbContext(typeof(apphouseContext))]
    partial class apphouseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("app_house.Models.Alquiler", b =>
                {
                    b.Property<int>("Alquilerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Alquilerid"), 1L, 1);

                    b.Property<int>("Casaid")
                        .HasColumnType("int");

                    b.Property<string>("Casaname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Clienteid")
                        .HasColumnType("int");

                    b.Property<string>("Clientename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAlquiler")
                        .HasColumnType("datetime2");

                    b.HasKey("Alquilerid");

                    b.HasIndex("Casaid");

                    b.HasIndex("Clienteid");

                    b.ToTable("Alquiler");
                });

            modelBuilder.Entity("app_house.Models.Casa", b =>
                {
                    b.Property<int>("Casaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Casaid"), 1L, 1);

                    b.Property<string>("Casaname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Dueñoname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("MontoF")
                        .HasColumnType("int");

                    b.Property<bool>("alquilada")
                        .HasColumnType("bit");

                    b.Property<bool>("eliminada")
                        .HasColumnType("bit");

                    b.Property<byte[]>("imagencasa")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("metros")
                        .HasColumnType("int");

                    b.HasKey("Casaid");

                    b.ToTable("Casa");
                });

            modelBuilder.Entity("app_house.Models.Cliente", b =>
                {
                    b.Property<int>("Clienteid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Clienteid"), 1L, 1);

                    b.Property<string>("Clienteapellido")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Clientename")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fechanacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Clienteid");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("app_house.Models.Devolver", b =>
                {
                    b.Property<int>("Devolverid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Devolverid"), 1L, 1);

                    b.Property<int>("Alquilerid")
                        .HasColumnType("int");

                    b.Property<int>("Casaid")
                        .HasColumnType("int");

                    b.Property<string>("Casaname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Clienteid")
                        .HasColumnType("int");

                    b.Property<string>("Clientename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaDevolucion")
                        .HasColumnType("datetime2");

                    b.HasKey("Devolverid");

                    b.HasIndex("Casaid");

                    b.HasIndex("Clienteid");

                    b.ToTable("Devolver");
                });

            modelBuilder.Entity("app_house.Models.Alquiler", b =>
                {
                    b.HasOne("app_house.Models.Casa", "Casa")
                        .WithMany()
                        .HasForeignKey("Casaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("app_house.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("Clienteid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Casa");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("app_house.Models.Devolver", b =>
                {
                    b.HasOne("app_house.Models.Casa", "Casa")
                        .WithMany()
                        .HasForeignKey("Casaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("app_house.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("Clienteid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Casa");

                    b.Navigation("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
